### PR TITLE
Added version functionality

### PR DESCRIPTION
**Pull request by gottsman**
It now prints version numbers with "--version" and properly adds the "__version__" property.

### CODE REVIEW

**Comment by sibson** [comment]
Generally, looks good,  I have few requests before I merge

1) could you post the output of vncdo --version 
2) could you also adjust https://github.com/sibson/vncdotool/blob/master/makefile#L18 so the release process continues to work
3) does this work for vnclog as well?

thanks

**Comment by gottsman** [comment]
Here is the output of vncdo/vnclog:

```
MacBook-Pro:Dinero kevin$ vncdotool --version
vncdotool 0.11.2
MacBook-Pro:Dinero kevin$ vnclog --version
vnclog 0.11.2
MacBook-Pro:Dinero kevin$ 
```

Need to work on the makefile patch next.

**Comment by gottsman** [comment]
I tried updating the makefile, but need a pointer... When I did "make release", I get errors. When I do "make version", works as expected.

```
MacBook-Pro:vncdotool kevin$ make version
python setup.py --version
0.11.2
MacBook-Pro:vncdotool kevin$ make release
nosetests tests/unit
make: nosetests: No such file or directory
make: *** [test] Error 1
MacBook-Pro:vncdotool kevin$
```

**Comment by sibson** [comment]
provided make version-2.0.1 properly updates __init__.py I think we will be in a good place.  'make release' requires you to have a python environment setup with the requirements-dev.txt

**Comment by gottsman** [comment]
This is all 100% new to me. Thanks for being patient. Set up my development environment with the requirements-dev.txt file. I think the version part is working as expected. I still may not have twine setup properly.

```
MacBook-Pro:vncdotool kevin$ vi vncdotool/__init__.py
MacBook-Pro:vncdotool kevin$ make release
nosetests tests/unit
..................................................
----------------------------------------------------------------------
Ran 50 tests in 0.089s

OK
git tag -a v0.11.5 -m"release version 0.11.5"
git push --tags
Counting objects: 1, done.
Writing objects: 100% (1/1), 167 bytes | 167.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To https://github.com/gottsman/vncdotool.git
 * [new tag]         v0.11.5 -> v0.11.5
python setup.py sdist
running sdist
running egg_info
writing requirements to vncdotool.egg-info/requires.txt
writing vncdotool.egg-info/PKG-INFO
writing top-level names to vncdotool.egg-info/top_level.txt
writing dependency_links to vncdotool.egg-info/dependency_links.txt
writing entry points to vncdotool.egg-info/entry_points.txt
reading manifest file 'vncdotool.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'vncdotool.egg-info/SOURCES.txt'
running check
creating vncdotool-0.11.5
creating vncdotool-0.11.5/tests
creating vncdotool-0.11.5/tests/functional
creating vncdotool-0.11.5/tests/functional/data
creating vncdotool-0.11.5/tests/unit
creating vncdotool-0.11.5/vncdotool
creating vncdotool-0.11.5/vncdotool.egg-info
copying files to vncdotool-0.11.5...
copying LICENSE.txt -> vncdotool-0.11.5
copying MANIFEST.in -> vncdotool-0.11.5
copying README.rst -> vncdotool-0.11.5
copying TODO.txt -> vncdotool-0.11.5
copying requirements-2.6-dev.txt -> vncdotool-0.11.5
copying requirements-2.6.txt -> vncdotool-0.11.5
copying requirements-dev.txt -> vncdotool-0.11.5
copying requirements.txt -> vncdotool-0.11.5
copying setup.cfg -> vncdotool-0.11.5
copying setup.py -> vncdotool-0.11.5
copying tests/__init__.py -> vncdotool-0.11.5/tests
copying tests/functional/test_proxy.py -> vncdotool-0.11.5/tests/functional
copying tests/functional/test_screen.py -> vncdotool-0.11.5/tests/functional
copying tests/functional/test_send_events.py -> vncdotool-0.11.5/tests/functional
copying tests/functional/data/example.png -> vncdotool-0.11.5/tests/functional/data
copying tests/functional/data/example_nocursor.png -> vncdotool-0.11.5/tests/functional/data
copying tests/functional/data/simple.png -> vncdotool-0.11.5/tests/functional/data
copying tests/unit/__init__.py -> vncdotool-0.11.5/tests/unit
copying tests/unit/mock.py -> vncdotool-0.11.5/tests/unit
copying tests/unit/test_client.py -> vncdotool-0.11.5/tests/unit
copying tests/unit/test_command.py -> vncdotool-0.11.5/tests/unit
copying vncdotool/__init__.py -> vncdotool-0.11.5/vncdotool
copying vncdotool/api.py -> vncdotool-0.11.5/vncdotool
copying vncdotool/client.py -> vncdotool-0.11.5/vncdotool
copying vncdotool/command.py -> vncdotool-0.11.5/vncdotool
copying vncdotool/loggingproxy.py -> vncdotool-0.11.5/vncdotool
copying vncdotool/pyDes.py -> vncdotool-0.11.5/vncdotool
copying vncdotool/rfb.py -> vncdotool-0.11.5/vncdotool
copying vncdotool.egg-info/PKG-INFO -> vncdotool-0.11.5/vncdotool.egg-info
copying vncdotool.egg-info/SOURCES.txt -> vncdotool-0.11.5/vncdotool.egg-info
copying vncdotool.egg-info/dependency_links.txt -> vncdotool-0.11.5/vncdotool.egg-info
copying vncdotool.egg-info/entry_points.txt -> vncdotool-0.11.5/vncdotool.egg-info
copying vncdotool.egg-info/requires.txt -> vncdotool-0.11.5/vncdotool.egg-info
copying vncdotool.egg-info/top_level.txt -> vncdotool-0.11.5/vncdotool.egg-info
Writing vncdotool-0.11.5/setup.cfg
Creating tar archive
removing 'vncdotool-0.11.5' (and everything under it)
twine upload dist/vncdotool-0.11.5.*
Invalid command: upload
make: *** [upload] Error 1
MacBook-Pro:vncdotool kevin$
```

**Comment by sibson** [comment]
Thanks for sticking with it.  I didn't get the markdown formatting right for my last comment which made it confusing.  You won't be able to ```make release``` because you don't have write access to pypi.  What you need to test is the new version command works properly.  Something like the following should work.

  > make version-1.1.1
  > cat vncdotool/__init__.py
  version = 1.1.1
  > make version
  1.1.1

**Comment by gottsman** [comment]
Corrected the makefile.... Looks like it works, but as you said, no pypi access.

**Comment by sibson** [comment]
thanks, ✨ 🍰 ✨

**Pull request merged**
